const $ = (s) => document.querySelector(s);
const canvas = $('#stars'), ctx = canvas.getContext('2d');
let stars = [], audioCtx;
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);stars=Array.from({length:Math.min(130,innerWidth/9)},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.6+.2,a:Math.random()}));}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight); stars.forEach((s,i)=>{s.a+=.008;ctx.fillStyle=`rgba(255,240,197,${.25+Math.abs(Math.sin(s.a))*.6})`;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill();});requestAnimationFrame(draw)}resize();draw();addEventListener('resize',resize);
addEventListener('pointermove',e=>{$('.cursor-glow').style.left=e.clientX+'px';$('.cursor-glow').style.top=e.clientY+'px'});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.15});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function pop(x=innerWidth/2,y=innerHeight/2){for(let i=0;i<90;i++){const d=document.createElement('i');d.className='confetti';d.style.cssText=`position:fixed;z-index:30;left:${x}px;top:${y}px;width:${5+Math.random()*7}px;height:${7+Math.random()*12}px;background:${['#ff8eaa','#f5c866','#bc8ae0','#fff'][i%4]};pointer-events:none;transform:rotate(${Math.random()*360}deg);transition:transform ${.7+Math.random()*.8}s cubic-bezier(.1,.7,.2,1),opacity 1.6s`;document.body.append(d);requestAnimationFrame(()=>{d.style.transform=`translate(${(Math.random()-.5)*550}px,${-80-Math.random()*420}px) rotate(${Math.random()*720}deg)`;d.style.opacity=0});setTimeout(()=>d.remove(),1700)}}
$('#confettiButton').onclick=e=>{pop(e.clientX,e.clientY);toast('رشّة سحر خاصة لكِ ✦')};$('#finalCelebrate').onclick=e=>{pop(e.clientX,e.clientY);toast('كل عام وأنتِ بخير يا أجمل حكاية!')};
let candles=5;document.querySelectorAll('.candle').forEach(c=>c.onclick=e=>{if(c.classList.contains('out'))return;c.classList.add('out');candles--;$('#candleCount').textContent=candles;if(candles){$('#cakePrompt').textContent='أمنية اختبأت بين النجوم... بقي '+candles}else{$('#cakePrompt').textContent='تحققت الأمنيات! سنة مليانة نور وفرح.';pop(e.clientX,e.clientY);toast('تمّ! احتفظنا بكل أمنياتك.')}});
document.querySelectorAll('.memory-card').forEach(card=>card.onclick=()=>{$('#memoryText').textContent=card.dataset.memory;$('#memoryModal').classList.add('show');$('#memoryModal').setAttribute('aria-hidden','false')});function close(){ $('#memoryModal').classList.remove('show');$('#memoryModal').setAttribute('aria-hidden','true')}$('#closeModal').onclick=close;$('#memoryModal').onclick=e=>e.target.id==='memoryModal'&&close();
$('#wish').oninput=e=>$('#charCount').textContent=e.target.value.length+' / 150';$('#wishForm').onsubmit=e=>{e.preventDefault();const wish=$('#wish').value.trim();if(!wish)return;$('#wishJar').insertAdjacentHTML('beforeend','<span class="new-star">✦</span>');e.target.reset();$('#charCount').textContent='0 / 150';toast('انطلقت أمنيتك إلى السماء ✦');pop(innerWidth*.35,innerHeight*.72)};
$('#soundButton').onclick=function(){if(!audioCtx){audioCtx=new AudioContext();}const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(523,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(784,audioCtx.currentTime+.5);g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.06,audioCtx.currentTime+.06);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.8);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.85);this.classList.toggle('playing');toast('لحن صغير لليلة الكبيرة ♪')};
